import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavigationBar from "./components/elements/navbar";
import Header from "./components/sections/header";
import PageLayout from "./components/templates/page-layout";
import "./globals.css";
import { getCFFooter } from "./helpers/contentful/get-cf-footer";
import { getHeader } from "./helpers/contentful/get-cf-header";
import { ThemeProvider } from "./provider/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [header, footer] = await Promise.all([getHeader(), getCFFooter()]);
  console.log("Header", header[0]);
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header logo={header[0]?.logo}>
              <NavigationBar links={header[0]?.navigationsCollection.items} />
            </Header>

            <main className="bg-gray-600 dark:bg-black">
              <PageLayout>{children}</PageLayout>
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
